<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
        @font-face {
            font-family: 'THSarabunNew';
            font-style: normal;
            font-weight: normal;
            src: url("{{ public_path('fonts/THSarabunNew.ttf') }}") format('truetype');
        }

        @font-face {
            font-family: 'THSarabunNew';
            font-style: normal;
            font-weight: bold;
            src: url("{{ public_path('fonts/THSarabunNew-Bold.ttf') }}") format('truetype');
        }

        body {
            font-family: "THSarabunNew";
            font-size: 16pt;
            line-height: 1.2;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .title {
            font-size: 24pt;
            font-weight: bold;
            margin-bottom: 5px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        table, th, td {
            border: 1px solid #333;
        }

        th {
            background-color: #f2f2f2;
            padding: 8px;
            font-weight: bold;
            text-align: center;
        }

        td {
            padding: 5px 10px;
            vertical-align: middle;
        }

        .text-center {
            text-align: center;
        }

        .footer {
            margin-top: 20px;
            font-size: 12pt;
            text-align: right;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="title">{{ $title }}</div>
        <div>Report Date: {{ $date }}</div>
    </div>

    <table>
        <thead>
            <tr>
                <th width="8%">No.</th>
                <th width="12%">Staff ID</th>
                <th width="30%">Full Name</th>
                <th width="30%">Email Address</th>
                <th width="20%">Joining Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($teachers as $key => $teacher)
                <tr>
                    <td class="text-center">{{ $key + 1 }}</td>

                    <td class="text-center">
                        {{-- Formats the ID as 001, 002, etc. --}}
                        {{ str_pad($teacher->id, 3, '0', STR_PAD_LEFT) }}
                    </td>

                    <td>{{ $teacher->name }}</td>
                    <td>{{ $teacher->email }}</td>

                    <td class="text-center">
                        @if (isset($teacher->join_date))
                            {{ \Carbon\Carbon::parse($teacher->join_date)->format('d/M/Y') }}
                        @else
                            {{ $teacher->created_at->format('d/M/Y') }}
                        @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by bikky
    </div>
</body>
</html>