<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
        @font-face {
            font-family: 'THSarabunNew';
            src: url("{{ public_path('fonts/THSarabunNew.ttf') }}") format('truetype');
        }

        body {
            font-family: "THSarabunNew";
            font-size: 16pt;
            line-height: 1.2;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        table,
        th,
        td {
            border: 1px solid #333;
        }

        th {
            background-color: #f2f2f2;
            padding: 8px;
            text-align: center;
            font-weight: bold;
        }

        td {
            padding: 6px 10px;
        }

        .text-center {
            text-align: center;
        }
    </style>
</head>

<body>
    <div class="header">
        <h2 style="margin: 0;">{{ $title }}</h2>
        <p style="margin: 5px 0;">Report Date: {{ $date }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th width="10%">No.</th>
                <th width="20%">Student ID</th>
                <th width="35%">Full Name</th>
                <th width="35%">Email</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($students as $key => $student)
                <tr>
                    <td class="text-center">{{ $key + 1 }}</td>
                    <td class="text-center">
                        {{-- แสดงเลข 001, 002 ตามที่คุณต้องการ --}}
                        {{ str_pad($student->id, 3, '0', STR_PAD_LEFT) }}
                    </td>
                    <td>{{ $student->name }}</td>
                    <td>{{ $student->email }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <div class="footer">
        Generated by bikky
    </div>

</body>

</html>
